myapp/urls.py
from django.urls import path 
from . import views
app_name=  'myapp'

urlpatterns = [
    path('', views.tables, name='table-page'),
    path('quiz/', views.quiz, name='quiz'),
    path('tough-quiz/', views.tough_quiz, name='tough-quiz'),
    path('toggle-closeness/<int:pk>', views.toggle_closeness, name='toggle-closeness'),
    path('toggle-decidiability/<int:pk>', views.toggle_decidiability, name='toggle-decidiability'),
    path('new-decidablity-note/', views.add_note_dec, name='new-decidablity-note'),
    path('new-closureproperty-note/', views.add_note_cp, name='new-closureproperty-note'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('myapp.urls')),
    path('admin/', admin.site.urls),
]

myapp/models.py
from django.db import models

class Language(models.Model):
    title = models.CharField(max_length=50)
    full_name = models.CharField(max_length=60, default='')

    def __str__(self):
        return self.title


class SetOperation(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title


class Problem(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title


class IsClosed(models.Model):
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    set_operation = models.ForeignKey(SetOperation, on_delete=models.CASCADE)

    is_closed = models.BooleanField(default=False)

    def __str__(self):
        if self.is_closed:
            return f"{self.language.title} is CLOSED under {self.set_operation.title}"
        return f"{self.language.title} is NOT CLOSED under {self.set_operation.title}"



class Decidiability(models.Model):
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)

    is_decidiable = models.BooleanField(default=False)

    def __str__(self):
        if self.is_decidiable:
            return f"{self.language.title} is DECIDIABLE under {self.problem.title}"
        return f"{self.language.title} is UNDECIDIABLE under {self.problem.title}"

class DecidiabilityNote(models.Model):
    text = models.CharField(max_length=500)

    def __str__(self):
        return f"{self.text[:30]}..."

class ClosurePropertyNote(models.Model):
    text = models.CharField(max_length=500)

    def __str__(self):
        return f"{self.text[:30]}..."
        

myapp/views.py
from django.shortcuts import redirect, render
from myapp.models import Language, Decidiability, Problem, IsClosed, SetOperation, DecidiabilityNote, ClosurePropertyNote
from django.urls import reverse
import random

def tables(request):
    languages = Language.objects.all()
    set_operations = SetOperation.objects.all()
    problems = Problem.objects.all()
    decidiabilities = Decidiability.objects.all()
    closeness = IsClosed.objects.all()

    decidiability_table = []
    closeness_table = []

    

    for problem in problems:
        temp_list = [problem.title]
        for language in languages:
            is_decidiable = Decidiability.objects.filter(language=language, problem=problem)[0]
            temp_list.append(is_decidiable)
        decidiability_table.append(temp_list)


    for set_operation in set_operations:
        temp_list = [set_operation.title]
        for language in languages:
            is_closed = IsClosed.objects.filter(language=language, set_operation=set_operation)[0]
            temp_list.append(is_closed)
        closeness_table.append(temp_list)

    return render(request, 'myapp/tables.html', {
        'languages': languages,
        'set_operations': set_operations,
        'problems': problems,
        'decidiabilities': decidiabilities,
        'closeness': closeness,
        'decidiability_table': decidiability_table,
        'closeness_table': closeness_table,
        'decidiability_notes': DecidiabilityNote.objects.all(),
        'closureproperty_notes': ClosurePropertyNote.objects.all(),
    })

def quiz(request):
    languages = Language.objects.all()
    problems = Problem.objects.all()
    set_operations = SetOperation.objects.all()
    decidiabilities = Decidiability.objects.all()
    closeness = IsClosed.objects.all()

    decidiability_table = []
    closeness_table = []

    for problem in problems:
        temp_list = [problem.title]
        for language in languages:
            is_decidiable = Decidiability.objects.filter(language=language, problem=problem)[0]
            temp_list.append(is_decidiable)
        decidiability_table.append(temp_list)


    for set_operation in set_operations:
        temp_list = [set_operation.title]
        for language in languages:
            is_closed = IsClosed.objects.filter(language=language, set_operation=set_operation)[0]
            temp_list.append(is_closed)
        closeness_table.append(temp_list)

    return render(request, 'myapp/quiz.html', {
        'languages': languages,
        'set_operations': set_operations,
        'problems': problems,
        'decidiabilities': decidiabilities,
        'closeness': closeness,
        'decidiability_table': decidiability_table,
        'closeness_table': closeness_table,
    })


def toggle_closeness(request, pk):
    if request.method=='POST':
        object = IsClosed.objects.filter(pk=pk)[0]
        object.is_closed = not object.is_closed
        # object.save()
        return redirect(reverse('myapp:table-page'))

def toggle_decidiability(request, pk):
    if request.method=='POST':
        object = Decidiability.objects.filter(pk=pk)[0]
        object.is_decidiable = not object.is_decidiable
        # object.save()
        return redirect(reverse('myapp:table-page'))

def tough_quiz(request):
    languages = Language.objects.all()
    problems = Problem.objects.all()
    set_operations = SetOperation.objects.all()
    decidiabilities = Decidiability.objects.all()
    closeness = IsClosed.objects.all()

    question_list = []

    langs = random.sample(set(languages), 3)
    probs = random.sample(set(problems), 3)
    ops = random.sample(set(set_operations), 3)

    for lang in langs:
        for prob in probs:
            p = Decidiability.objects.filter(language=lang, problem=prob)[0]
            question = f"Is <u>{prob.title}</u> problem of <u>{lang.title}</u> is decidiable?"
            if p.is_decidiable:
                answer = f"<u>{prob.title}</u> problem of <u>{lang.title}</u> is DECIDABLE."
            else:
                answer = f"<u>{prob.title}</u> problem of <u>{lang.title}</u> is NOT DECIDABLE."
            question_list.append({'question': question, 'answer': answer})

    for lang in langs:
        for op in ops:
            p = IsClosed.objects.filter(language=lang, set_operation=op)[0]
            question = f"Is <u>{lang.title}</u> closed under <u>{op.title}</u>?"
            if p.is_closed:
                answer = f"<u>{lang.title}</u> closed under <u>{op.title}</u>."
            else:
                answer = f"<u>{lang.title}</u> NOT closed under <u>{op.title}</u>."
            question_list.append({'question': question, 'answer': answer})
    random.shuffle(question_list)
    return render(request, 'myapp/quiz2.html', {'question_list': question_list})


def add_note_dec(request):
    if request.method == 'POST':
        text = request.POST.get('text')
        DecidiabilityNote.objects.create(text=text)
        return redirect(reverse('myapp:table-page'))

def add_note_cp(request):
    if request.method == 'POST':
        text = request.POST.get('text')
        ClosurePropertyNote.objects.create(text=text)
        return redirect(reverse('myapp:table-page'))

myapp/templates/myapp/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap Icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    {% block page_style %}{% endblock page_style %}
    <title>
        {% block page_title %}{% endblock page_title %}
    </title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'myapp:table-page' %}">TOC</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:quiz' %}">Quiz</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:tough-quiz' %}">Tough Quiz</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                
            </ul>
            <div class="d-flex">
                
            </div>
            </div>
        </div>
    </nav>
    <div class="container">
    {% block page_content %}{% endblock page_content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block page_style %}{% endblock page_style %}

{% block page_title %}Tables{% endblock page_title %}


{% block page_content %}



{% endblock page_content %}

myapp/templates/myapp/quiz.html
{% extends 'myapp/base.html' %}

{% block page_style %}
<style>

table, th, td {
  border: 1px solid black;
  text-align:center;
}
tr.t1 > th:first-child,
tr.t1 > td:first-child,
tr.t2 > th:first-child,
tr.t2 > td:first-child{
    width: 500px;
}
td{
    height: 50px;
}
td.box{
    width: 50px;
}
.box{
    cursor: pointer;
    font-size: 30px;
}
.box:hover{
    background-color: whitesmoke;
    font-weight: bold;
}
</style>

{% endblock page_style %}

{% block page_title %}Tables{% endblock page_title %}


{% block page_content %}

<h1>Decidiability</h1>
<table>
    <tr class="t1">
        <th>Problems</th>
        {% for language in languages %}
        <th>{{language.title}}</th>
        {% endfor %}
    </tr>
    {% for row in decidiability_table %}
    <tr class="t1">
    {% for col in row %}
        <td class="{% if forloop.first %} row-header {% else %} box {% endif %}">
            {% if forloop.first %}
                {{col}}
            {% else %}
                <div class="t-data invisible">
                    <div class="answer">
                    {% if col.is_decidiable %}
                        <i class="bi bi-check text-success"></i>
                    {% else %}
                        <i class="bi bi-x text-danger"></i>
                    {% endif %}
                    </div>
                </div>
            {% endif %}
        </td>
    {% endfor %}
    </tr>
    {% endfor %}
</table>
<br>
<hr>
<h1>Set Operaitons. Is Closed? </h1>
<table>
    <tr class="t2">
        <th>Operation</th>
        {% for language in languages %}
        <th>{{language.title}}</th>
        {% endfor %}
    </tr>
    {% for row in closeness_table %}
    <tr class="t2">
    {% for col in row %}
        <td class="{% if forloop.first %} row-header {% else %} box {% endif %}">
            {% if forloop.first %}
                {{col}}
            {% else %}
                <div class="t-data invisible">
                    <div class="answer">
                    {% if col.is_closed %}
                        <i class="bi bi-check text-success"></i>
                    {% else %}
                        <i class="bi bi-x text-danger"></i>
                    {% endif %}
                    </div>
                </div>
            {% endif %}
        </td>
    {% endfor %}
    </tr>
    {% endfor %}
</table>
<br>

<script>
    var boxes = document.querySelectorAll('.box')
    console.log(boxes.length)
    boxes.forEach(box=>{
        box.addEventListener('dblclick', e=>{
            console.log('clicked')
            box.querySelector('.t-data').classList.remove('invisible')
        })
    })

</script>
{% endblock page_content %}

myapp/templates/myapp/quiz2.html
{% extends 'myapp/base.html' %}


{% block page_title %}Tough Quiz{% endblock page_title %}

{% block page_content %}

    {% for question in question_list %}
        <div class="border mb-3 p-3 mt-3">
            <h3>{{question.question|safe}}</h3>
            <button class="btn btn-primary mb-2" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{forloop.counter}}" aria-expanded="false" aria-controls="collapse-{{forloop.counter}}">
                View Answer
            </button>
            <div class="collapse" id="collapse-{{forloop.counter}}">
                Answer:
                <div class="">
                    {{question.answer|safe}}
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock page_content %}

myapp/templates/myapp/tables.html
{% extends 'myapp/base.html' %}

{% block page_style %}
<style>

table, th, td {
  border: 1px solid black;
  text-align:center;
}
tr.t1 > th:first-child,
tr.t1 > td:first-child,
tr.t2 > th:first-child,
tr.t2 > td:first-child{
    width: 500px;
}
td{
    height: 50px;
}
td.box{
    width: 50px;
}
.box{
    cursor: pointer;
    font-size: 30px;
}
.box:hover{
    background-color: whitesmoke;
    font-weight: bold;
}
</style>

{% endblock page_style %}

{% block page_title %}Tables{% endblock page_title %}


{% block page_content %}

<h1>Decidability</h1>
<table>
    <tr class="t1">
        <th>Problems</th>
        {% for language in languages %}
        <th>{{language.title}}</th>
        {% endfor %}
    </tr>
    {% for row in decidiability_table %}
    <tr class="t1">
    {% for col in row %}
        <td class="{% if forloop.first %} row-header {% else %} box {% endif %}">
            {% if forloop.first %}
                {{col}}
            {% else %}
                <div class="t-data">
                    <div class="answer">
                    {% if col.is_decidiable %}
                        <i class="bi bi-check text-success"></i>
                    {% else %}
                        <i class="bi bi-x text-danger"></i>
                    {% endif %}
                    </div>
                    <form action="{% url 'myapp:toggle-decidiability' col.pk %}" method="POST" class="d-none" data-isclosed="{{col.pk}}">
                        {% csrf_token %}
                        {% if col.is_decidiable %}
                            <button class="btn"type="submit"><i class="bi bi-x text-danger"></i> <i class="bi bi-question-circle"></i></button>
                        {% else %}
                            <button class="btn"type="submit"><i class="bi bi-check text-success"></i> <i class="bi bi-question-circle"></i></button>
                        {% endif %}
                    </form>
                </div>
            {% endif %}
        </td>
    {% endfor %}
    </tr>
    {% endfor %}
</table>
<p class="lead">Points to remember:</p>
<ul>
{% for note in decidiability_notes %}
    <li>{{note.text|safe}}</li>
{% endfor %}
</ul>
<form action="{% url 'myapp:new-decidablity-note' %}" method="POST">
    {% csrf_token %}
    <div class="input-group mb-3">
        <input type="text" class="form-control" name="text" placeholder="Add new point">
        <button class="btn btn-outline-secondary" type="submit" id="">Save</button>
    </div>
</form>
<br>
<hr>
<h1>Set Operaitons. Is Closed? </h1>
<table>
    <tr class="t2">
        <th>Operation</th>
        {% for language in languages %}
        <th>{{language.title}}</th>
        {% endfor %}
    </tr>
    {% for row in closeness_table %}
    <tr class="t2">
    {% for col in row %}
        <td class="{% if forloop.first %} row-header {% else %} box {% endif %}">
            {% if forloop.first %}
                {{col}}
            {% else %}
                <div class="t-data">
                    <div class="answer">
                    {% if col.pk == 64 or col.pk == 65 or col.pk == 66 %}
                        <i class="bi bi-question-circle"></i>
                    {% elif col.is_closed %}
                        <i class="bi bi-check text-success"></i>
                    {% else %}
                        <i class="bi bi-x text-danger"></i>
                    {% endif %}
                    </div>
                    <!--<form action="{% url 'myapp:toggle-closeness' col.pk %}" method="POST" class="d-none" data-isclosed="{{col.pk}}">-->
                    <!--    {% csrf_token %}-->
                    <!--    {% if col.is_closed %}-->
                    <!--        <button class="btn"type="submit"><i class="bi bi-x text-danger"></i> <i class="bi bi-question-circle"></i></button>-->
                    <!--    {% else %}-->
                    <!--        <button class="btn"type="submit"><i class="bi bi-check text-success"></i> <i class="bi bi-question-circle"></i></button>-->
                    <!--    {% endif %}-->
                    <!--</form>-->
                </div>
            {% endif %}
        </td>
    {% endfor %}
    </tr>
    {% endfor %}
</table>
<p class="lead">Points to remember:</p>
<ul>
{% for note in closureproperty_notes %}
    <li>{{note.text|safe}}</li>
{% endfor %}
</ul>
<form action="{% url 'myapp:new-closureproperty-note' %}" method="POST">
    {% csrf_token %}
    <div class="input-group mb-3">
        <input type="text" class="form-control" name="text" placeholder="Add new point">
        <button class="btn btn-outline-secondary" type="submit" id="">Save</button>
    </div>
</form>
<br>

<script>
    var boxes = document.querySelectorAll('.t-data')
    boxes.forEach(box=>{
        box.addEventListener('dblclick', e=>{
            var ans = box.querySelector('.answer')
            var form = box.querySelector('form')
            ans.classList.add('d-none')
            form.classList.remove('d-none')
        })
        box.addEventListener('blur', e=>{
            var ans = box.querySelector('.answer')
            var form = box.querySelector('form')
            ans.classList.remove('d-none')
            form.classList.add('d-none')
        })
    })

</script>
{% endblock page_content %}